Limelight Vision
momentumfrc/2019DeepSpace pull request #4
Opened 2019-05-18 02:18 UTC by JacobAaCook

2019-05-18 02:47 UTC, terbos90803 requested changes

2019-05-18 02:47 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    double turnRequest = posX * TURN_K;
You'll likely want to use MoPID for these since you'll want to specify targets (e.g. 0 for X and some positive value for dist).  You'll also likely want the PID control bundled up instead of just a naked P.

2019-05-18 02:47 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/Limelight.java
> +  public double validTarget = NetworkTableInstance.getDefault().getTable("limelight").getEntry("tv").getDouble(0);
This statement is executed once at class construction time.  Thus, the tv entry will only be read once and validTarget will be whatever it is when the robot boots.
Same goes for xOffset and yOffset.

It's ok to create NetworkTableEntry members at class construction, but you will need to getDouble periodically, or you will need to attach listeners to the Entries.

2019-05-18 02:47 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/Limelight.java
> +  public static final double RANGE_X = 29.8;
I'm assuming you pulled these values from the Limelight example.  You should document what they mean and why they were chosen.

2019-05-18 02:47 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/Limelight.java
> +  public double targetDistance = (height) / (angle);
As above, these values are only being calculated once, ever.  If that's the intent, then fine.  But otherwise this math needs to be in a method that gets called periodically.

2019-05-18 02:47 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    posData = limelight.targetPos();
limelight.targetPos can return null.  You must validate that posData is non-null before using it below.

2019-05-18 02:47 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/Limelight.java
> +  public double[] targetPos() {
returning bundled values as an array is a really bad code smell.  There is no implicit checking for the size of the array.  You are restricted to only values of a single type.  The caller has to "just know" what each of the slots in the array represents.  There are hideous long-term maintenance issues.

Just don't do this.

It's far better to create an immutable class that holds all the values with correct names and types.

2019-05-18 02:47 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/Limelight.java
> +  public boolean atTarget() {
Having targetIsValid, targetPos, and atTarget broken out as separate methods opens you up to multithreaded race conditions.  You have no guarantees that the internal values won't change between calls so you can't know if the call to targetIsValid actually relates to the data returned from targetPos.

The way this should be handled is that the Limelight subsystem has one synchronized call to get a snapshot of the current state as an immutable object.  That object then has methods to determine if it's valid and if so, what position the target is at.

2019-05-21 17:25 UTC, terbos90803 requested changes

2019-05-21 17:25 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/vision/Limelight.java
> +      if (x <= X_ERR && y <= Y_ERR && d + DIST_ERR <= TARGET_DIST || d - DIST_ERR >= TARGET_DIST) {
The DIST_ERR calculation should be done as  abs(difference) <= constant, just like x and y

2019-05-21 17:25 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/vision/LimelightData.java
> +public class LimelightData {
I don't think you quite understood what I meant by an "immutable class".  We should discuss tonight about the flow of data, the lifetime of the different class objects and why they should be split that way.

2019-05-22 14:31 UTC, terbos90803 requested changes

2019-05-22 14:31 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +  public static final double RANGE_X = 29.8; // The range of values given by "tx" is from -29.8 to 29.8 degrees
These values are specific to the Limelight and thus should be located in the Limelight class.

Always think about who "owns" a piece of information.  All ownership should be clear and localized.  It's ok to ask another class for a piece of information, like a constant, as long as the "truth" is owned by the correct class.

This is called the "Information Expert" principle.  A specific class should always be the owner of all of its related data.  Any other class that needs that data needs to ask the expert instead of having its own copy.

2019-05-22 14:31 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/vision/LimelightData.java
> +public class LimelightData {
This class was folded into Limelight and this file should be deleted.

2019-05-22 14:31 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/vision/Limelight.java
> +    public boolean targetMet(){
This doesn't appear to be complete.  The implementation of targetMet needs to move from the out class into here.

2019-05-22 14:31 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/subsystems/vision/Limelight.java
> +  public LimelightData data;
There is no reason for Limelight to ever hold onto a LimelightData.  Remove this member.

2019-05-22 14:31 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    turnErr = data.xCoord();
The first thing that needs to happen in execute() is to get a fresh LimelightData.  Make that call and hold the data as a local variable in this method.

2019-05-23 00:42 UTC, terbos90803 requested changes

2019-05-23 00:42 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/Robot.java
> +import frc.robot.subsystems.vision.Limelight.LimelightData;
Extra import?  Remove if not needed.

2019-05-23 00:42 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    limelight.getData();
LimelightData data = limelight.getData();

2019-05-23 00:42 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +  private LimelightData data;
LimelightData should not be a member of VisionDrive.  Remove.

2019-05-23 00:42 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
>      turnErr = data.xCoord();
All of these variables should be local to this method.  There is no reason for most of these to be class members.

2019-05-23 00:42 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    return data.targetMet();
There does need to be some way to connect the data retrieved in execute to the answer to the isFinished question.

While it's possible to hold data as a class member, I would recommend instead calling targetMet in execute and holding the result as a boolean class member.  Then just return that boolean here.

2019-05-23 04:08 UTC, JacobAaCook commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    return data.targetMet();
so have a separate boolean in VisionDrive? Is there any reason why to, the way I see it is, targetMet() will return True or False, if we have a separate boolean that will just echo whatever targetMet() is saying. So it seems like more steps than should be needed. Unless doing it this way is some cause for a race condition?

2019-05-23 15:31 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    return data.targetMet();
The structure of a Command (VisionDrive extends Command) is that is has an execute() method and an isFinished() method.  These two methods are called separately, but need to be consistent in their actions/responses.  To provide this consistency, there needs to be some connection between the two.  This is best handled by using private members of the class, which are shared between the two methods.

So you have some choices to make about the form of those shared members.  For this situation, you have two basic options:

1. get a fresh copy of LimelightData on every call to execute and do *some* of the processing on that data there (i.e. drive commands).  Hold onto that LimelightData as a class member and do additional processing on it during the call to isFinished (i.e. targetMet).
1. get a fresh copy of LimelightData on every call to execute and do *all* processing on that data there, discarding the LimelightData when execute exits.  Save the results of targetMet as a boolean class member to be used during the anticipated future call to isFinished.

Either one of these options will achieve the desired result, but the preference is to choose option 2 for these reasons:

- In general, as much processing as possible should be handled in the execute class.  The designers of the Command pattern expected this call to be more expensive than any other since it should be doing all the work.
- isFinished is effectively an accessor.  It should not be doing any calculations that should have been done during execute.  All it needs to do is reference the results of those calculations and return that pre-computed boolean.

2019-05-23 15:34 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    double turnRequest = Utils.map(turnErr, -RANGE_X, RANGE_X, -1.0, 1.0);
You haven't checked data.isValid to see if the coordinates are valid.

You need to make sure that the data is valid and useful before you act on it.  If you don't have valid data, the best choice is to force all movement requests to 0 for safety.

2019-05-23 18:33 UTC, terbos90803 requested changes
Getting really close.  Down to the last few nits.

2019-05-23 18:33 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +  public static final double RANGE_X = Limelight.RANGE_X; // The range of values given by "tx" is from -29.8 to 29.8
While it may seem convenient to have these local copies of the Limelight values, there is no penalty in simply using the Limelight class values directly when needed.  Doing so reduces the amount of redundant clutter here.

2019-05-23 18:33 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
>    public double limelightTurn;
Are these unused?  If so, remove.

2019-05-23 18:33 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
> +    boolean valid = data.valid();
Why do you make local copies of all of these values?  There is little to no penalty in calling accessors, so it's more concise to just call them inline where needed, especially if they're only used once.
The biggest justifications for making a local copy is if you are trying to address:

- performance across multiple uses
- readability in the case of very long calling strings, particularly when using multiple times
- readability if the name of the accessor is quite different from the intended local usage

In this case, valid and valid are a match and only used once, so should just be inline.
turnErr and xCoord are sufficiently different that you could argue in favor of making the local to enhance readability.

2019-05-24 02:31 UTC, terbos90803 requested changes
Pretty sure this is the last one.

2019-05-24 02:31 UTC, terbos90803 commented on 2019RobotCodeDeepSpace/src/main/java/frc/robot/commands/VisionDrive.java
>      met = data.targetMet();
met needs to be qualified by valid as well.  Can't be at the target if you can't see it.

2019-05-24 04:30 UTC, terbos90803 approved these changes

2019-05-31 00:16 UTC, merged